/**
 * Human-takeover guard for DMs - added 2026-09-24 (Ravi).
 *
 * Ravi's ask: "if a human (not the AI) replies in a DM, the AI should go
 * quiet - just monitor and log, not reply - until the customer gets no
 * human reply for 4 working hours, at which point the AI takes back over as
 * a stand-in, reassuring the customer the team will definitely reply."
 * Scoped to DMs only, per Ravi's own wording ("kisi bhi Dm me") - public
 * comment threads are unaffected.
 *
 * HOW THIS WORKS (read before changing):
 * Zernio's webhook only fires for CUSTOMER-sent events (message.received) -
 * it never tells us when a human manually replies from Instagram/Zernio's
 * own inbox UI. There is no real-time signal for "a human just replied".
 *
 * So this piggybacks on traffic we already get: every time a new customer
 * DM arrives, we do ONE extra read of that conversation's most recent
 * messages (Zernio's listInboxConversationMessages - the same read API
 * api/backfill.js already uses) and check whether the latest "outgoing"
 * message in there was one WE sent. We know what we sent because every
 * AI-sent reply is fingerprinted into Redis right after sending (see
 * markAiSent, called from api/webhook.js). If the latest outgoing message
 * doesn't match a fingerprint we hold, it wasn't generated by this bot - a
 * human must have typed it directly into Instagram/Zernio.
 *
 * This deliberately avoids a cron/scheduled-poll design across every
 * conversation (Vercel's cron frequency and Zernio's own API limits are
 * both unverified from here, and constantly polling every conversation
 * would multiply API calls even during quiet periods). This only costs one
 * extra Zernio read per incoming customer DM, which we're already
 * processing anyway.
 *
 * HARD LIMITATION Ravi confirmed and should keep in mind: this can only
 * ever detect a human reply that happens INSIDE the same Instagram/WhatsApp
 * thread. A phone call (which Ravi confirmed the team also uses, e.g. the
 * seller flow's "Neel ji aapko call karenge") leaves no trace here and can
 * never be detected by this or any other code - there is no way to build
 * around that with the tools available.
 */

const crypto = require('crypto');
const { listInboxConversationMessages } = require('./zernioClient');

function redisConfig() {
  return {
    url: (process.env.REDIS_KV_REST_API_URL || process.env.REDIS_URL || '').replace(/\/$/, ''),
    token: process.env.REDIS_KV_REST_API_TOKEN || process.env.REDIS_K_TOKEN || '',
  };
}

async function redisCommand(path) {
  const { url, token } = redisConfig();
  if (!url || !token) throw new Error('Redis credentials are not configured');
  const res = await fetch(`${url}${path}`, { headers: { Authorization: `Bearer ${token}` } });
  if (!res.ok) throw new Error(`Redis error ${res.status}`);
  return res.json().catch(() => ({}));
}

function textHash(text) {
  return crypto.createHash('sha256').update(String(text || '').trim().toLowerCase().replace(/\s+/g, ' ')).digest('hex').slice(0, 24);
}

const AI_SENT_TTL_SECONDS = 24 * 60 * 60; // look-back window per check is tiny (last ~15 messages); generous on purpose
const HUMAN_ACTIVE_TTL_SECONDS = 7 * 24 * 60 * 60;

// Called from api/webhook.js right after an AI reply is successfully sent,
// so future takeover checks recognise it as our own message rather than
// mistaking it for a human reply.
async function markAiSent(memoryId, text) {
  try {
    await redisCommand(`/set/${encodeURIComponent(`gemrishi:ai-sent:${memoryId}:${textHash(text)}`)}/1/EX/${AI_SENT_TTL_SECONDS}`);
  } catch (err) {
    console.error('[humanTakeoverGuard] markAiSent failed:', err.message);
  }
}

async function getHandoffState(memoryId) {
  try {
    const data = await redisCommand(`/get/${encodeURIComponent(`gemrishi:human-active:${memoryId}`)}`);
    if (!data?.result) return null;
    return JSON.parse(data.result);
  } catch (err) {
    console.error('[humanTakeoverGuard] getHandoffState failed:', err.message);
    return null;
  }
}

async function setHandoffState(memoryId, state) {
  try {
    await redisCommand(`/set/${encodeURIComponent(`gemrishi:human-active:${memoryId}`)}/${encodeURIComponent(JSON.stringify(state))}/EX/${HUMAN_ACTIVE_TTL_SECONDS}`);
  } catch (err) {
    console.error('[humanTakeoverGuard] setHandoffState failed:', err.message);
  }
}

async function clearHandoffState(memoryId) {
  try {
    await redisCommand(`/del/${encodeURIComponent(`gemrishi:human-active:${memoryId}`)}`);
  } catch (err) {
    console.error('[humanTakeoverGuard] clearHandoffState failed:', err.message);
  }
}

// Working-hours math - 10 AM - 8 PM IST, all 7 days (same window as the
// handoff note in api/webhook.js). IST has no DST, fixed +5:30, so a plain
// offset is safe without a timezone library.
const IST_OFFSET_MINUTES = 5 * 60 + 30;
const WORK_START_MIN = 10 * 60;
const WORK_END_MIN = 20 * 60;
const RESUME_AFTER_WORKING_MINUTES = 4 * 60; // 4 working hours, per Ravi

// Minutes of *working-hours* time (10AM-8PM IST) that have elapsed between
// two real instants - a plain wall-clock diff would overcount overnight
// gaps, which matters since the whole point is "4 working hours", not
// "4 calendar hours".
function workingMinutesElapsed(fromMs, toMs) {
  if (toMs <= fromMs) return 0;
  let cursor = fromMs;
  let total = 0;
  let guard = 0;
  while (cursor < toMs && guard < 60) { // safety cap - never loop more than ~2 months of days
    guard += 1;
    const istMs = cursor + IST_OFFSET_MINUTES * 60000;
    const istDate = new Date(istMs);
    const dayStartIstMs = Date.UTC(istDate.getUTCFullYear(), istDate.getUTCMonth(), istDate.getUTCDate(), 0, 0, 0);
    const windowStart = dayStartIstMs + WORK_START_MIN * 60000 - IST_OFFSET_MINUTES * 60000;
    const windowEnd = dayStartIstMs + WORK_END_MIN * 60000 - IST_OFFSET_MINUTES * 60000;
    const segStart = Math.max(cursor, windowStart);
    const segEnd = Math.min(toMs, windowEnd);
    if (segEnd > segStart) total += (segEnd - segStart) / 60000;
    const nextWindowStart = windowStart + 24 * 60 * 60000;
    cursor = cursor < windowEnd ? windowEnd : nextWindowStart;
  }
  return total;
}

/**
 * Checks this DM conversation for a human-authored outgoing message and
 * returns the current takeover decision for the customer message that just
 * arrived.
 *
 * Returns { silence, justDetectedHuman, resumed }:
 *   - silence=true  -> api/webhook.js must NOT generate/send an AI reply.
 *   - justDetectedHuman=true -> a human message was found just now (useful
 *     for logging/notes).
 *   - resumed=true -> 4 working hours passed with no further human reply;
 *     the handoff state was cleared and normal AI replies resume.
 */
async function checkHumanTakeover({ apiKey, conversationId, accountId, memoryId }) {
  let humanDetectedNow = false;
  try {
    const page = await listInboxConversationMessages({ apiKey, conversationId, accountId, limit: 15, sortOrder: 'desc' });
    const messages = Array.isArray(page?.messages) ? page.messages : [];
    const latestOutgoing = messages.find((m) => m?.direction === 'outgoing' && String(m?.message || '').trim());
    if (latestOutgoing) {
      const found = await redisCommand(`/get/${encodeURIComponent(`gemrishi:ai-sent:${memoryId}:${textHash(latestOutgoing.message)}`)}`).catch(() => null);
      if (!found?.result) humanDetectedNow = true;
    }
  } catch (err) {
    console.error('[humanTakeoverGuard] Zernio read failed; assuming no takeover:', err.message);
    return { silence: false, justDetectedHuman: false, resumed: false };
  }

  if (humanDetectedNow) {
    // A human is actively engaged right now - (re)start the silence window,
    // clearing any pending resume-deadline so it never fires mid-conversation
    // while the human is still replying.
    await setHandoffState(memoryId, { since: new Date().toISOString(), pendingSince: null });
    return { silence: true, justDetectedHuman: true, resumed: false };
  }

  const state = await getHandoffState(memoryId);
  if (!state) return { silence: false, justDetectedHuman: false, resumed: false }; // no handoff on record - normal AI flow

  // A handoff is on record but no NEW human message just now - this is a
  // customer message arriving while we're meant to stay quiet. Start (or
  // keep) the "customer waiting" clock and decide whether 4 working hours
  // have passed since their first unanswered message in this silent window.
  const now = Date.now();
  if (!state.pendingSince) {
    await setHandoffState(memoryId, { ...state, pendingSince: new Date().toISOString() });
    return { silence: true, justDetectedHuman: false, resumed: false };
  }

  const elapsed = workingMinutesElapsed(new Date(state.pendingSince).getTime(), now);
  if (elapsed >= RESUME_AFTER_WORKING_MINUTES) {
    await clearHandoffState(memoryId);
    return { silence: false, justDetectedHuman: false, resumed: true };
  }
  return { silence: true, justDetectedHuman: false, resumed: false };
}

module.exports = { checkHumanTakeover, markAiSent, workingMinutesElapsed };
